apiVersion: apps/v1
kind: Deployment
metadata:
  name: verification-service
  namespace: pc-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: verification-service
  template:
    metadata:
      labels:
        app: verification-service
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: verification-service
                topologyKey: "kubernetes.io/hostname"

      containers:
        - name: verification-service-cont
          image: chillmadiguys/verification-service:v1.1.1
          ports:
            - containerPort: 8000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "400m"
              memory: "512Mi"

        
          envFrom:
            - configMapRef:
                name: pc-config-global
            - secretRef:
                name: pc-secrets-global

          volumeMounts:
            - name: verification-service-volume
              mountPath: /app/uploads
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 30
          #   timeoutSeconds: 5
          #   failureThreshold: 3
 
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          #   timeoutSeconds: 5
          #   failureThreshold: 3
 
      volumes:
        - name: verification-service-volume
          persistentVolumeClaim:
            claimName: pc-upload-pvc